version: '3.8'

services:
  e-banking-db:
    image: postgres:13
    container_name: e-banking-db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ENSA
      POSTGRES_PASSWORD: ENSA
      POSTGRES_DB: E_BANKING
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: